site:
  title: Example Assertions Documentation
  start_page: documentation::index.adoc

content:
  sources:
    - url: https://gitlab.univ-nantes.fr/E203173Q/example-assertions
      start_path: examples/docs/antora


ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./examples/docs/antora/supplemental-ui


asciidoc:
  attributes:
    page-pagination: top bottom
    icons: font


